### ISSUE TITLE
works when extension is '.db'

### ISSUE THREAD

**Issue by sjsepan3** [yy0931/sqlite3-editor#1]
Very Nice -- Like it!

ISSUE:
But I ran into an issue trying to open some existing '.sqlite' files. I tried looking at some of Mozilla Firefox's files, 'places.sqlite' for example, and the extension would not recognize it. Then I noticed your extension's tab in VSCode  mentioned '.db' under Custom Editors, Filename Pattern. So I copied and renamed the file as places.sqlite.db, and it worked instantly. Note I had already checked my Python version...
```
python3 -V
Python 3.10.6
```
...and path...
```
which python3
/usr/bin/python3
```
...which I added to the extension's settings. It was not until I renamed the file that I could open it.

EXPECTED BEHAVIOR:
Would be handy if it recognized the database with other extensions.

ENVIRONMENT:
Linux Mint 21.0
Cinnamon 5.4.12
kernel 5.15.0.56-generic
VSCode 1.74.1 / VSCodium 1.74.1
Python 3.10.6

**Comment by yy0931** [comment]
Thank you for reporting it. I'll fix it soon.

**Comment by yy0931** [comment]
I've published a new version (v1.0.3) which adds `.sqlite` and `.sqlite3` as default file patterns, and I've also included instructions on how to associate other files with this VSCode extension in README.

**Comment by sjsepan3** [comment]
Excellent -- after the update to 1.0.3, the extension now offers me an editor for Sqlite3 when opening the '.sqlite' files. And the 'Usage' section describing further associations in a nice addition!
Thank You.
