### ISSUE TITLE
runtime error at `webview.queryError.readwrite`

### ISSUE THREAD

**Issue by Alien-Alfa** [yy0931/sqlite3-editor#12]
database disk image is malformed
Method: table_schema
database disk image is malformed
Method: table_schema

**Comment by yy0931** [comment]
Can the database be opened using the SQLite 3 CLI (`sqlite3`)? If it is corrupted, you may have a chance of recovering data with the [.recover](https://www.sqlite.org/cli.html#recover) command.
If you are able to connect to the database with the SQLite 3 CLI and execute `SELECT * FROM sqlite_master;` successfully, but you are unable to open the database with the extension, please let me know.
