### ISSUE TITLE
Powershell doesn't recognize command inside a pair of apostrophes 'C:\WINDOWS\py.EXE' 

### ISSUE THREAD

**Issue by Yang-z** [yy0931/sqlite3-editor#14]
When I try to export a table to scv, editor generate the fellow command for me:
`'C:\WINDOWS\py.EXE' -m sqlite_utils query 'o:\data\my.db3' 'SELECT * FROM "table1"' --csv > out.csv`
ps throws errors, if I correct the command as:
`C:\WINDOWS\py.EXE -m sqlite_utils query 'o:\data\my.db3' 'SELECT * FROM "table1"' --csv > out.csv`
It works.
I don't know whether there's some settings I can modify to make the former command to work. Or it's a bug of the editor.

**Comment by yy0931** [comment]
Thank you for catching the bug! It is a bug of the editor, and I haven't notice it because I don't often use Windows.

**Comment by yy0931** [comment]
I have fixed this in 1.0.68. However, there may be another issue related to newline characters, which I'll check later.
