### ISSUE TITLE
[FEATURE-REQUEST] Quick delete option

### ISSUE THREAD

**Issue by BoomRaccoon** [yy0931/sqlite3-editor#18]
Looks like a great plugin from the first few minutes of use but it's a little annoying that I always have to commit a delete. I understand that it's a best practice to ask the user for confirmation but I'd love to have a setting where the 'Delete' will just go through without confirmation.

**Comment by yy0931** [comment]
Thanks for the feedback. You can alt+click row numbers to select multiple rows and then commit, which should be a bit more efficient. I forgot to add a hint for that feature. Does that solve your problem?

**Comment by BoomRaccoon** [comment]
I saw the feature for alt+click but the context menu I get does not list Delete as an option there is only
- Copy selection as JSON
- Copy selection CSV
Would I have to insert a command and commit?

**Comment by yy0931** [comment]
I meant alt+clicking 5, 6, 7 in this image, not the cells.

![image](https://github.com/yy0931/sqlite3-editor/assets/54441600/660ded97-60ba-4a9f-bcf1-acda949657cd)

**Comment by BoomRaccoon** [comment]
Clicking on the rowIDs will give a a context menu that has delete, but clicking "Delete" will set the selection to the last one you clicked and the command will be "DELETE FROM YourTableName WHERE rowid=XXX ". So I am back to deleting them one by one and pressing commit for each.
Hope I am not just being dense 😅

**Comment by yy0931** [comment]
You may be pressing `alt + right click` instead of `alt + left click`. When you press `alt + left click` on two row numbers, the text below the table should change from `DELETE FROM ... WHERE rowid = 1` to `DELETE FROM ... WHERE ROWID IN (1, 2)`.

It seems the current UI is much more unintuitive than I thought. I'll change the "DELETE" button to display a yes/no/`do not ask me again` confirmation dialog like other apps instead.

**Comment by BoomRaccoon** [comment]
Oh boy. I didn't look further down the README, typical case of RTFM 😅
I expected the docs for the basic features at the top so I didn't read through it.

This obviously solves my problem of deleting multiple entries
Sorry for the waste of time.
