### ISSUE TITLE
Select any char parser 

### ISSUE THREAD

**Issue by KrillDes** [yy0931/sqlite3-editor#19]
Hi! Default char parser is ',' but i want any char parser (: ; . ' / ...)

Do u can add feature? @yy0931 👍

**Comment by yy0931** [comment]
Which feature are you referring to: "import table from CSV," "export table to CSV," or "copy selection as CSV" (select a range, then press Ctrl+C)? Also, couldn't "import/export table from/to JSON" or "copy selection as JSON" serve your needs?

**Comment by KrillDes** [comment]
> Which feature are you referring to: "import table from CSV," "export table to CSV," or "copy selection as CSV" (select a range, then press Ctrl+C)? Also, couldn't "import/export table from/to JSON" or "copy selection as JSON" serve your needs?

I mean import from CSV. I have file with tabs and colon...

Finaly i do parser myself for import CSV table so... will be cool if you add any chars to import for CSV

**Comment by yy0931** [comment]
I've added a notification that explains how to change the delimiter to v1.0.80.
