### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by SevaShpun** [yy0931/sqlite3-editor#2]
I'm trying to open the database.sqlite3 file and I'm getting this error.

> TypeError: Cannot read properties of null (reading 'records')

**Comment by yy0931** [comment]
Thank you for providing the error message.
Wasn't a stack trace shown in the error message? If not, could you provide the error shown in the developer tools, which you can open by selecting "Developer: Open Webview Developer Tools" in the command palette (f1 or ctrl+shift+p or cmd+shift+p)?
It would be helpful if you could also share the database file.

**Comment by yy0931** [comment]
Thank you for reporting the error. I could reproduce it on windows.

**Comment by yy0931** [comment]
I've fixed the bug in v1.0.14. The bug was caused by selecting a Python binary compiled with an older version of SQLite. I've added a notice in the README specifying the minimum required version of SQLite bundled with Python, and updated the extension so that it won't select incompatible versions of Python.

**Comment by SevaShpun** [comment]
Yesterday the error "**TypeError: Cannot read properties of null (reading 'records')**" was displayed where I marked it with a green rectangle. And there was no message to the red block yesterday. It showed up today.

DevTools
![scr2](https://user-images.githubusercontent.com/23108549/209561908-cbfdc5db-8cb7-4e75-b626-46f6f99d2a24.png)


Database (unzip)
[database.zip](https://github.com/yy0931/sqlite3-editor/files/10303931/database.zip)

**Comment by yy0931** [comment]
The error says that the system does not have a version of Python supported by the extension, so you should install the latest version of Python. What operating system are you using? If you are using Windows, you can try installing Python 3.10 from the Microsoft Store. After installation, you can check the version of SQLite bundled with Python using the following command. the output should be above 3.37.0. Please let me know if you have Python version >= 3.6 bundled with sqlite >= 3.37.0 and you still get the error.

```shell
python3 -c "import sqlite3; print(sqlite3.sqlite_version)"
```

---
Ошибка гласит, что система не имеет версии Python, поддерживаемой расширением, поэтому вам следует установить последнюю версию Python. Какая у вас операционная система? Если вы используете Windows, вы можете попробовать установить Python 3.10 из Microsoft Store. После установки вы можете проверить версию SQLite, прилагаемую к Python, с помощью следующей команды. Выходные данные должны быть выше 3.37.0. Пожалуйста, сообщите мне, если у вас есть Python версии >= 3.6 с sqlite >= 3.37.0, и вы все еще получаете ошибку.

```shell
python3 -c "import sqlite3; print(sqlite3.sqlite_version)"
```

**Comment by SevaShpun** [comment]
> The error says that the system does not have a version of Python supported by the extension, so you should install the latest version of Python. What operating system are you using? If you are using Windows, you can try installing Python 3.10 from the Microsoft Store. After installation, you can check the version of SQLite bundled with Python using the following command. the output should be above 3.37.0. Please let me know if you have Python version >= 3.6 bundled with sqlite >= 3.37.0 and you still get the error.
> 
> ```shell
> python3 -c "import sqlite3; print(sqlite3.sqlite_version)"
> ```
> 
> Ошибка гласит, что система не имеет версии Python, поддерживаемой расширением, поэтому вам следует установить последнюю версию Python. Какая у вас операционная система? Если вы используете Windows, вы можете попробовать установить Python 3.10 из Microsoft Store. После установки вы можете проверить версию SQLite, прилагаемую к Python, с помощью следующей команды. Выходные данные должны быть выше 3.37.0. Пожалуйста, сообщите мне, если у вас есть Python версии >= 3.6 с sqlite >= 3.37.0, и вы все еще получаете ошибку.
> 
> ```shell
> python3 -c "import sqlite3; print(sqlite3.sqlite_version)"
> ```

**OS:** _Ubuntu 20.04.5 LTS_
**Python:** _3.8.10_
**sqlite3 --version:** _3.31.1_

`python3 -c "import sqlite3; print(sqlite3.sqlite_version)" # result 3.31.1`

Apparently it means I have a problem in my version "sqlite3". When I try to update "sqlite3" it tells me that this is the latest version.

**Comment by yy0931** [comment]
I've reduced the minimum required version of SQLite to v3.8.7.1 (2014-10-29), and uploaded v1.0.15 of the extension.

I added code to parse `CREATE TABLE` statements with regex when [`PRAGMA table_list`](https://www.sqlite.org/pragma.html#pragma_table_list), which was introduced in 3.37.0, isn't available.

**Comment by SevaShpun** [comment]
Thank you! Now everything works as it should. 

Will you publish the source code in the repository?
