### ISSUE TITLE
Feature Request: Dropdown for Foreign Keys on New Record Entry

### ISSUE THREAD

**Issue by tsunosekai** [yy0931/sqlite3-editor#20]
Thank you for the wonderful plugin.
I think it would be incredibly useful to have a dropdown menu for selecting data from the referenced table when adding a new record to a table with a foreign key. The existing feature, where hovering the mouse over an element with a foreign key displays the corresponding row from the referenced table, is very handy and I anticipate a similar look and feel for this proposed feature.

**Comment by gdaunlam** [comment]
I think one alternative could be to implement in the input field a suggestion for autocompleting values that belong to the referenced table. (input autocomplete)

**Comment by yy0931** [comment]
I prototyped a part of the feature a while ago so I can release it under an experimental flag now, though there should be bugs since I haven't tested much.

https://github.com/yy0931/sqlite3-editor/assets/54441600/23cc3225-a38f-4c4d-8d89-53c0d8865aff

**Comment by yy0931** [comment]
You can use the feature on v1.0.99 by adding `"sqlite3-editor.ui.experimental.foreignKeyDropdown": true` to VSCode's settings.

**Comment by gdaunlam** [comment]
¿Is it possible that this feature is not available for custom selects?

**Comment by yy0931** [comment]
Do you mean that you want to change the data in a table by clicking a cell then a dropdown after executing a SELECT statement that contains a rowid column (like `SELECT rowid, * FROM table1`)? If so, then yes, it's possible to implement that.

**Comment by tsunosekai** [comment]
Thank you.
I turned on the settings and used it and it works ideal!
This editor has become the best sqlite editor for me!

**Comment by tsunosekai** [comment]
I agree with gdaunlam's request.
It will be more convenient.

**Comment by gdaunlam** [comment]
I just reread your message, and I realize that I had understood something different. What I was referring to is that the suggestions for foreign keys are currently only visible when editing a table. However, when trying to edit a view or a custom select, the suggestions don't work, even for custom selects that display the same information as the query editor. I've attached examples.

Here it works.
<img width="692" alt="image" src="https://github.com/yy0931/sqlite3-editor/assets/70639509/274c9ba5-f59e-4cdf-b1d9-e3cad8c66b12">

Here it doesn't.
<img width="692" alt="image" src="https://github.com/yy0931/sqlite3-editor/assets/70639509/3347f5c0-e638-41d6-ba5e-3ff22b031cc5">

In any case, this would be unnecessary if the feature you're suggesting of clicking on a cell and then on a dropdown menu to execute a SELECT statement containing a rowid column could be done from a view or a custom select.
However, I believe that would be much more complex.

**Comment by yy0931** [comment]
> when trying to edit a view or a custom select, the suggestions don't work

Yes, that's the issue I was referencing in my previous comment.

In my previous comment, I was trying to describe the following sequence of events:
1. First, you open a query editor by clicking the "Query Editor" button.
2. Next, you run a SELECT statement that includes a rowid column in the editor.
3. After you do this, you select a table cell.
4. Then you want to modify data in the table using a dropdown menu that is shown under the UPDATE statement.

(By the way I'll fix the broken HTML in "Updating data through ..." in next version.)

**Comment by gdaunlam** [comment]
Okay, it's clear, thank you very much. This plugin is greatly improving my day-to-day work today. Any contribution or help that we can give you, let us know. Greetings!

**Comment by yy0931** [comment]
I've implemented https://github.com/yy0931/sqlite3-editor/issues/20#issuecomment-1711110657, along with [other improvements](https://marketplace.visualstudio.com/items/yy0931.vscode-sqlite3-editor/changelog),  in v1.0.100.

**Comment by gdaunlam** [comment]
It works perfectly, the feature is greatly appreciated. I'm not sure how it will work with multiple rowids, but it feels very clean at first glance. Thank you very much!

**Comment by yy0931** [comment]
>It works perfectly, the feature is greatly appreciated.

Thanks!

> multiple rowids

Perhaps the help message, which says you need to add a rowid to edit, was misleading? Every table that doesn't use the [`WITHOUT ROWID`](https://www.sqlite.org/withoutrowid.html) option has an implicit [ROWID](https://www.sqlite.org/rowidtable.html) column. Even if you create a rowid column, as you do in [#20 (comment)](https://github.com/yy0931/sqlite3-editor/issues/20#issuecomment-1711652592), there is a separate implicit ROWID associated with the table that can be referred to as `oid` or `_rowid_`. I wanted to say in the message that you need to SELECT the implicit rowid column, not that you need to create a rowid column.

```sqlite
sqlite> create table t(x);
sqlite> insert into t values (1);
sqlite> select rowid, * from t;
rowid|x
1|1
```

**Comment by gdaunlam** [comment]
I interpret what you mentioned, but when trying it, the error continued to appear. I'll share my table schema with you in case it helps in any way.

<img width="1156" alt="image" src="https://github.com/yy0931/sqlite3-editor/assets/70639509/08077487-f11c-43fc-b14a-9327d0c32633">

```sql
CREATE TABLE "record" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT, 
    "title" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'nth' ,
    "type" TEXT NOT NULL DEFAULT 'daft',
    "order" INTEGER,
    "expiration" TEXT, 
    "topic" TEXT, 
    "eta" TEXT,
    "created_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(status) REFERENCES status(name)
    FOREIGN KEY(type) REFERENCES type(name)
    FOREIGN KEY(topic) REFERENCES topic(path)
);
(I recently changed from 'rowid' to 'id' to confirm my issue.)
```

**Comment by yy0931** [comment]
I was misunderstanding SQLite's behavior, specifically the following part. I can fix that.

> In the exception, the INTEGER PRIMARY KEY becomes an alias for the rowid.
> https://www.sqlite.org/rowidtable.html

**Comment by gdaunlam** [comment]
Okay, since my use is more personal, it's not a problem for me initially, but I'll keep it in mind. I'll let you know if I find anything else!

**Comment by yy0931** [comment]
The bug should be fixed in v1.0.107.

**Comment by gdaunlam** [comment]
I see that now it's not necessary to query using rowid; great job, thank you very much!
I tried to look at some of the code. Are you migrating your backend to Rust? How's the experience so far?

**Comment by yy0931** [comment]
I migrated the Python code to Rust in v1.0.91, although it remains on an independent branch. I chose Rust largely due to my familiarity with the language, having contributed to (non-OSS) small Rust projects in the past, so the experience so far has been positive.

**Comment by yy0931** [comment]
I have been considering of adding dropdowns within table cells, but after prototyping, I noticed the overlap between click actions of cell selection and dropdown opening made the UI harder to use, so I close this issue for now.
