### ISSUE TITLE
runtime error at `webview.renderApp`

### ISSUE THREAD

**Issue by panexe** [yy0931/sqlite3-editor#21]
no such table: main.$TA_CDESCRIND
Method: table_schema
Error: no such table: main.$TA_CDESCRIND
Method: table_schema
    at se (https://file .vscode-resource.vscode-cdn.net/home/lars/.vscode/extensions/yy0931.vscode-sqlite3-editor-1.0.85/webview/assets/index-3225ee99.js:122:501)

**Comment by yy0931** [comment]
~~I've succeeded in reproducing it with this dataset https://www.kaggle.com/datasets/rtatman/188-million-us-wildfires?resource=download, I'll fix it soon.~~ I noticed it's a different error.

**Comment by yy0931** [comment]
I noticed that the extension displays the error when a view references a non-existent table. Is that your problem?

**Comment by panexe** [comment]
Yeah, that's possible. I've been playing around with creating some larger tables and move them randomly around. Both are prob. Not the best conditions. Probably my fault, sorry for the inconvenience.  

But on this topic, is there something to trick to make the plugin handle larger tables better, it always get pretty slowed down when I reach a couple GB. But they wouldn't have to be shown all at once, or am I missing something?

**Comment by yy0931** [comment]
> Yeah, that's possible. I've been playing around with creating some larger tables and move them randomly around. Both are prob. Not the best conditions. Probably my fault, sorry for the inconvenience.

No problem. I think the error message was confusing, so I'll work on improving it.

> it always get pretty slowed down when I reach a couple GB

This is because the extension counts the number of rows with `SELECT COUNT(*) FROM <table>` to position the scrollbar handle, which is slow on large tables. I haven't fixed it yet because most SQLite users work with small tables, but I can address this issue by disabling the scrollbar handle on larger tables.

**Comment by yy0931** [comment]
I've improved the error handling and added a limit to `SELECT COUNT(*) FROM <table>` in v1.0.86.

![image](https://github.com/yy0931/sqlite3-editor/assets/54441600/f4f3f7a5-b0fb-44bb-8521-c4a7ceb9a3c5)

**Comment by yy0931** [comment]
@panexe, I've read your feedback.

Regarding the performance issue, does setting "sqlite3-editor.ui.recordCountingLimit": 500000 in VSCode's settings mitigate your problem? Actually, there are several performance issues on edge cases, such as tables with very long texts or tables with many columns, so I'm not sure if recordCountingLimit works for you. I've been improving performances in some edge cases, but I'll see if I can enhance performance further next month, after finishing the port from Python to Rust (https://github.com/yy0931/sqlite3-editor/tree/rust-backend).
