### ISSUE TITLE
Added feature to extend protocols of links with Ctrl+click or context menu item

### ISSUE THREAD

**Issue by deivid-mudafy** [yy0931/sqlite3-editor#23]
Associated with the feature https://github.com/yy0931/sqlite3-editor/issues/16, it would be a good idea to include shortcuts for protocols like tcp://, file://, or others, such as links to applications, e.g., vscode://.

**Comment by yy0931** [comment]
Thank you for your request.
However, I'm uncertain whether it's worthwhile to implement it, as it's unclear if there are any users who store URI paths or application URIs (e.g., 'file:///foo/bar.txt' or 'vscode://file/foo/bar.txt'). Have you come across any database that does this? I will be happy to implement this feature there are real needs.

**Comment by deivid-mudafy** [comment]
Thank you for responding!
I have a use case for file URLs, migrating .md files that currently serve as task lists and notes to .sqlite. The idea is to emulate the functionality provided by .md files today by using links to files relative to the vscode workspace, for example:
\[links](/docs/otherFolder/doc4.mdx)

In the short term, I will be working on a frontend to manage notes, but today your plugin is the frontend I need.

**Comment by deivid-mudafy** [comment]
You're welcome, and thank you for your response.
I found this feature more complex than the question I posed because what I'm really looking for is the ability to interpret the content of a TEXT-type field as formatted markdown, ended up solving this with another plugin that allows me to access files based on their path.
Thanks for your time and for providing this plugin as it is!
