### ISSUE TITLE
The extension has been disabled because it does not support virtual workspaces.

### ISSUE THREAD

**Issue by kvolarichmaps** [yy0931/sqlite3-editor#3]
Cannot use this with database files in GitHub.  This is needed.

**Comment by yy0931** [comment]
Thanks for the advice. I'll check if it'll work in virtual workspaces.

**Comment by yy0931** [comment]
I've adapted the extension to virtual workspaces and it appears to be working. I'll release it after doing some more tests, especially for concurrent accesses.

**Comment by yy0931** [comment]
Version 1.0.26 includes a fix for this issue. Please let me know if there are any issues, as I don't regularly use virtual workspaces.
