### ISSUE TITLE
Possibility of going back after go to source record.

### ISSUE THREAD

**Issue by gdaunlam** [yy0931/sqlite3-editor#32]

**Comment by yy0931** [comment]
That is a good idea. I'll work on it.

**Comment by yy0931** [comment]
In the latest version, `Go to Source Record` and `Open <foreign key>` buttons save the current table state as a tab. The tab bar is visible only when you have used the foreign key related buttons, or when `"sqlite3-editor.ui.alwaysDisplayTabs"` is true.

I also experimented with web browser-like go back/forward feature, but I found it cluttered the UI.

![](https://raw.githubusercontent.com/yy0931/sqlite3-editor/main/tabs.png)

**Comment by gdaunlam** [comment]
Hello, thank you for everything!
I see that when you go to the record source from a custom query, the new tab doesn't appear.
Then, if you click on the query tag to return to the table view, the tabs appear.
I apologize for any confusion. It seems like the rest of the feature is working fine.

**Comment by yy0931** [comment]
Thanks for the catch! I've fixed it in v1.0.128.
