### ISSUE TITLE
Possibility to insert into table while in custom query view.

### ISSUE THREAD

**Issue by gdaunlam** [yy0931/sqlite3-editor#34]
<img width="870" alt="image" src="https://github.com/yy0931/sqlite3-editor/assets/70639509/38fa9ec4-b0eb-4c2d-ad01-0395684024a6">

**Comment by gdaunlam** [comment]
It's true, it's not difficult to reach the insertion view.
The problem is that when you want to save the record, since you're in a custom query and haven't selected a table (nor can you select one without exiting the query), the insertion doesn't generate any results.

**Comment by yy0931** [comment]
Yes, I know that now. I misread the title, commented, and quickly deleted it.

**Comment by yy0931** [comment]
I've implemented this feature in v1.0.148.
