### ISSUE TITLE
Ability to navigate to a record's references.

### ISSUE THREAD

**Issue by gdaunlam** [yy0931/sqlite3-editor#35]
<img width="532" alt="image" src="https://github.com/yy0931/sqlite3-editor/assets/70639509/99c50ac4-593b-4b85-afd6-3a58e50f0960">
<img width="528" alt="image" src="https://github.com/yy0931/sqlite3-editor/assets/70639509/1cfb38f2-6cc6-44c7-b5d2-0e4ea54b175f">

I envision a selectable option in the right-click context menu, where upon selection, it prompts you to specify the table to navigate to (containing a reference). Upon navigation, you'll arrive at the table filtered by the reference column.

**Comment by yy0931** [comment]
I've implemented this feature in v1.0.168. Now, you can right-click or press Shift + F12 (or Shift + Alt + F12) on a value in PRIMARY KEY or UNIQUE columns to find references.
