### ISSUE TITLE
Add 'wrap record content' option in the column management menu.

### ISSUE THREAD

**Issue by gdaunlam** [yy0931/sqlite3-editor#36]
<img width="857" alt="image" src="https://github.com/yy0931/sqlite3-editor/assets/70639509/a6a29838-4f5e-438d-b664-c00b8aa92ced">
<img width="246" alt="Captura de Pantalla 2023-10-15 a la(s) 00 28 57" src="https://github.com/yy0931/sqlite3-editor/assets/70639509/8fccc538-daf2-4426-8c83-b85ab981231b">
<img width="361" alt="image" src="https://github.com/yy0931/sqlite3-editor/assets/70639509/f7280de2-9adf-49d7-a798-d1d5bad5629d">

**Comment by yy0931** [comment]
I've implemented this in v1.0.137.

![image](https://github.com/yy0931/sqlite3-editor/assets/54441600/8531f120-1b4a-4b01-bca1-3aead8cd2769)

You can drag here to resize rows.

![image](https://github.com/yy0931/sqlite3-editor/assets/54441600/db9b4ffa-fe96-4058-a9e7-4ed63d53d11b)
