### ISSUE TITLE
Failed to load resources. This issue can occur after an extension update. Please try reopening the window.

### ISSUE THREAD

**Issue by qingbenpu** [yy0931/sqlite3-editor#40]
The following error appears in vs code in Ubuntu: Failed to load resources. This issue can occur after an extension update. Please try reopening the window.
I have tried other sqlite3 related plugins and they work fine. I don't think there is a problem with your plugin, maybe it is my recent improper operation of the Ubuntu system that caused this error, but I do not have the ability to find and solve this problem.
![Uploading D_(Q]GW7WKWK[Y}MEL@SCFM.png…]()

**Comment by qingbenpu** [comment]
![D_(Q GW7WKWK Y}MEL@SCFM](https://github.com/yy0931/sqlite3-editor/assets/64781789/d067833a-5f65-4da5-8381-102b4c55457c)

**Comment by qingbenpu** [comment]
After downgrading to version 1.0.90, I was able to use the extension normally. Versions 1.0.147 and 1.0.146 cannot be used, and I'm not sure about other versions.

**Comment by yy0931** [comment]
I was unable to reproduce the issue on Ubuntu 22.04 (x64).
Could it be possible that you are using an outdated version of Ubuntu or an uncommon CPU architecture?

Also, could you check if there are any errors in:
- the `SQLite3 Editor` section of the Output View (press `(Fn+) F1` then `Output: Focus on Output View`), or
- the `active-frame (index.html)` section of the `Console` tab in the Webview Developer Tools (open the extension's editor, press `(Fn+) F1` then `Developer: Open Webview Developer Tools`)?

![image](https://github.com/yy0931/sqlite3-editor/assets/54441600/56c5ec48-a113-432a-af96-5f9f31654de1)

![image](https://github.com/yy0931/sqlite3-editor/assets/54441600/e58cd035-a78e-4a99-8744-59128d9d836c)

**Comment by Fredyy90** [comment]
![image](https://github.com/yy0931/sqlite3-editor/assets/1572327/beb74a80-0803-4ee4-8a47-1d55ad991dfa)
I'm running into the same issue, extension is not usable currently, might be related to the failing loading of a dependency, why isn't the bundled with the extension rightaway?

cdn.jsdelivr.net seems to be completey broken for me rightnow, www.jsdelivr.net is reachable but cdn.jsdelivr.net isn't

**Comment by yy0931** [comment]
Thanks for the info! I didn't notice it wasn't bundled. I'll fix it later today.

**Comment by yy0931** [comment]
I've fixed it in v1.0.148. The cause was that I hadn't read "By default all sources come from CDN" in https://www.npmjs.com/package/@monaco-editor/loader#config.
