### ISSUE TITLE
Insert_Into doesnt work anymore!

### ISSUE THREAD

**Issue by Gatos90** [yy0931/sqlite3-editor#41]
After latest Release, Cant select anything anymore on Insert_Into. After selecting ist stays empty.

**Comment by yy0931** [comment]
Thank you for reporting the issue.
To clarify, is the issue that you are unable to select the INSERT statement and column names as text by dragging the mouse cursor? If so, I made it unselectable intentionally, but I can revert it.

**Comment by Gatos90** [comment]
When i try to select it in the dropdown, it doesnt work anymore.
![Screenshot 2023-12-01 143527](https://github.com/yy0931/sqlite3-editor/assets/54571782/df3fce94-87f1-43db-a23d-66ec7ad773c8)
![Screenshot 2023-12-01 114755](https://github.com/yy0931/sqlite3-editor/assets/54571782/ebffbbcc-1f70-4d91-a914-1ae8855efc0c)
Trying to Select. 

![Screenshot 2023-12-01 143527](https://github.com/yy0931/sqlite3-editor/assets/54571782/df3fce94-87f1-43db-a23d-66ec7ad773c8)

**Comment by yy0931** [comment]
I see. I've just found the bug that caused the issue. v1.0.150, which will be released in a few minutes, should fix that.

**Comment by Gatos90** [comment]
> I see. I've just found the bug that caused the issue. v1.0.150, which will be released in a few minutes, should fix that.

Awesome. Thank u!
