### ISSUE TITLE
Wrong rowid

### ISSUE THREAD

**Issue by vizam** [yy0931/sqlite3-editor#42]
The left column is supposed to be rowid right ? But hovering over it,  shows some kind of offset, after manipulating database. I tried another viewer, showing the right  state

![image](https://github.com/yy0931/sqlite3-editor/assets/21689719/83c0b198-8162-4492-b62b-015210c93df5)

**Comment by yy0931** [comment]
The leftmost column displays the offsets in the result of the SELECT statement. It always start at 1. The tooltip reveals the [rowid](https://www.sqlite.org/rowidtable.html) in the rowid table. Note that the rowid does not always start at 1. Does this answer your question?
