### ISSUE TITLE
keydropdownlimit configuration

### ISSUE THREAD

**Issue by esfingex** [yy0931/sqlite3-editor#43]
Where or how can I configure this option. thank you

**Comment by yy0931** [comment]
It is in the VSCode's settings:

![image](https://github.com/yy0931/sqlite3-editor/assets/54441600/dd52c553-17de-4abe-90eb-4a78ae0606fb)

![image](https://github.com/yy0931/sqlite3-editor/assets/54441600/874d0da6-f6d7-49c7-8923-5317f86daf3f)
