### ISSUE TITLE
Support for JSON field types

### ISSUE THREAD

**Issue by itviewer** [yy0931/sqlite3-editor#44]
Currently JSON fields are binary and cannot be edited

**Comment by yy0931** [comment]
I'm sorry, but I'm not quite sure what your issue is.
Are you referring to [JSONB](https://sqlite.org/draft/jsonb.html)? If so, as mentioned below the input, it is currently read-only, but editing support will be implemented after its official release.
If you are talking about regular JSON, although [SQLite does not have a specific JSON data type](https://www.sqlite.org/datatype3.html#type_affinity), you should be able to edit JSON data by clicking on the "TEXT" button.

**Comment by itviewer** [comment]
Thank you for your reply. 
I encountered a very strange thing. I don’t know if it is a problem with my environment or a problem with sqlite3-editor. I have uploaded my sqlite test file as attachment.
When I open it with sqlite3-editor, some of the columns in the first row are displayed as hexadecimal, but the exact same content in the second row can be displayed as text.
The following screenshots are opened using sqlite3-editor
![ksnip_20240106-01](https://github.com/yy0931/sqlite3-editor/assets/1397840/7a371198-3573-4d86-9f06-cf61ba74e852)
The following screenshots are opened using Navicat, and there is no problem
![ksnip_20240106-02](https://github.com/yy0931/sqlite3-editor/assets/1397840/f007e7a0-b40d-455c-bdd7-6dbfb8c07141)

the sqlite file

[anylink.zip](https://github.com/yy0931/sqlite3-editor/files/13849781/anylink.zip)

**Comment by yy0931** [comment]
It seems the data in the first row is saved as BLOB. Was the record inserted by another application? If this is a common issue, I can consider adding a feature to treat BLOB data that is parsable as UTF-8 as TEXT.

![image](https://github.com/yy0931/sqlite3-editor/assets/54441600/2bbda2d2-51c6-40cb-bd59-ee70eca6ceca)

**Comment by itviewer** [comment]
Yes, the first line is inserted by another application (Navicat opens without problems) and the second line is the first line that I copied manually in Navicat

**Comment by itviewer** [comment]
Should it be understood this way? If the application directly stores the byte array of json content, it is actually blob. If the application stores the string representation of json content, it is actually text. There is no real meaning of the JSON type？

**Comment by yy0931** [comment]
Yes, see this section: https://www.sqlite.org/json1.html#interface_overview

**Comment by itviewer** [comment]
Thanks, now I know this should be handled by another application!
