### ISSUE TITLE
Visual indication that long running query is still in progress

### ISSUE THREAD

**Issue by fofiddy** [yy0931/sqlite3-editor#46]
I executed a query that was performing a quite involved process and while query was executing for over a minute there was no feedback/indication from the plugin that the query was still executing.  Later, after a couple of minutes when the query completed, I noticed a small toast message flash at the bottom of the screen.  However, while the query was running I assumed something had gone wrong.

Thanks for all the hard work on this plugin.  It is great.

**Comment by yy0931** [comment]
It is an easy fix, so it will be fixed in the next release.

**Comment by yy0931** [comment]
Resolved in version 1.0.162. The feature to interrupt long running queries will be added in later versions.
