### ISSUE TITLE
Additional column filter options

### ISSUE THREAD

**Issue by fofiddy** [yy0931/sqlite3-editor#47]
It would be helpful to have more column filtering options.  See Excel for examples.  Greater than, less than, ranges, etc. for integers. Null/Not null values, Present a list of distinct values for checkbox selection, etc.  Refer to Excel column filtering options for expansive examples.

Nice work!

**Comment by yy0931** [comment]
Thanks. I'll implement it when I have time, although the priority is low since this can be done using SELECT statements in the query editor.

**Comment by yy0931** [comment]
I've added a button for specifying arbitrary SQL expressions for column filters. This may not be user-friendly for those new to SQL, so I'm considering adding buttons to initialize SQL expressions for basic operations such as <, >, etc., in later versions.

![image](https://github.com/yy0931/sqlite3-editor/assets/54441600/25af4688-3e2d-45c8-a2a9-bf6daffc94db)

**Comment by yy0931** [comment]
I forgot to mention that the [Group by Value](https://marketplace.visualstudio.com/items?itemName=yy0931.vscode-sqlite3-editor#table-view-group-by-value) feature can be seen as "a list of distinct values for checkbox selection."
