### ISSUE TITLE
error

### ISSUE THREAD

**Issue by nonstop13** [yy0931/sqlite3-editor#48]
This latest version gives this type of error please fix it as soon as possible 
"win32-x64 is not supported. Please request it on a [GitHub Issues](https://github.com/yy0931/sqlite3-editor/issues/new). In the meantime, you can [downgrade](https://code.visualstudio.com/updates/v1_30#_install-previous-versions) the extension to v1.0.90, which uses Python instead of a native binary. Note that v1.0.90 is not maintained, so it does not contain newer features and bug fixes available in later versions."

**Comment by yy0931** [comment]
I've just confirmed the latest version of the extension works on my Windows environment. That error indicates the binary file is missing, so I wonder if the binary file was accidentally deleted or removed by antivirus software.
Is there a file named `sqlite3-editor-win32-x64.exe` in `<home directory>\.vscode\extensions\yy0931.vscode-sqlite3-editor-<version number>\bin`? You can open that folder by running `ii ~\.vscode\extensions\yy0931.vscode-sqlite3-editor-*\bin` in PowerShell.

**Comment by yy0931** [comment]
I have updated the error message for missing binaries in version 1.0.180.

I'll close this issue for now due to inactivity, but if you are still experiencing the issue, please feel free to provide more details.
