### ISSUE TITLE
sea orm failed

### ISSUE THREAD

**Issue by miaomiao1992** [yy0931/sqlite3-editor#52]
after i used this plugin，sea-orm 0.12.14 running failed in rust

**Comment by miaomiao1992** [comment]
![IMG_4624](https://github.com/yy0931/sqlite3-editor/assets/59018630/1091a7fe-c926-4d03-ad13-3be12567e55a)
![IMG_4623](https://github.com/yy0931/sqlite3-editor/assets/59018630/cebe3054-cf2d-47f8-985a-9ac2d88a9636)
![IMG_4622](https://github.com/yy0931/sqlite3-editor/assets/59018630/1bd9076d-db28-4e0b-8d56-250c948e00b0)

**Comment by miaomiao1992** [comment]
unable to open database file? what is wrong?

**Comment by yy0931** [comment]
It appears that Visual Studio Code is running as administrator, as suggested by the window title. Is this intentional? I wonder if it caused the database file to have permissions not accessible to an ordinary user.

**Comment by miaomiao1992** [comment]
> It appears that Visual Studio Code is running as administrator, as suggested by the window title. Is this intentional? I wonder if it caused the database file to have permissions not accessible to an ordinary user.

thanks! it’s ok now. it is because of reading permission.

the vscode run the project using powershell,  and my project is shared as “共享文件夹”，so there is some permission problem.

**Comment by miaomiao1992** [comment]
it’ ok now.  thanks again.

![IMG_4626](https://github.com/yy0931/sqlite3-editor/assets/59018630/6e0f657c-2075-4ae4-876f-d8d0cfeac854)
