### ISSUE TITLE
Make the extension available on other platforms?

### ISSUE THREAD

**Issue by anthonymclaughlin** [yy0931/sqlite3-editor#53]
Is it possible to have the extension available via the [Open VSX Registry](https://open-vsx.org/)?, this would make it available on:

- [Project IDX](https://idx.dev/)
- [Stackblitz](https://stackblitz.com/)
- [VSCodium](https://vscodium.com/)
- etc.

Thanks.

**Comment by yy0931** [comment]
I don't use these editors, and the Eclipse account required by the Open VSX Registry seems to publicly display the email address. Additionally, I couldn't delete the account. I don't like such a site... Perhaps I'll reconsider if these editors become more popular.
