### ISSUE TITLE
Vulnerability: Unsupported JRE

### ISSUE THREAD

**Issue by Segelzwerg** [yy0931/sqlite3-editor#54]
Nessus Scanners reports there is an unsupported JRE Version

```
The following Java JRE installation is unsupported :

  Path              : ***/.vscode/extensions/yy0931.vscode-sqlite3-editor-1.0.184/webview/node_modules/monaco-editor/min/vs/basic-languages/java
  Installed version : 1.0.184_0_
  Latest versions   : 1.11.x / 1.17.x / 1.20.x
  Support dates     : No support dates are available.
```

**Comment by yy0931** [comment]
This extension doesn't include Java JRE.

The 'path'  only contains JavaScript files for syntax highlighting java code (https://github.com/microsoft/monaco-editor/tree/main/src/basic-languages/java), and the 'installed version' is not Java version but the extension's version.
