### ISSUE TITLE
[improvement] Adding access to the application from the left side menu

### ISSUE THREAD

**Issue by djedu28** [yy0931/sqlite3-editor#57]
Hi, thanks for the tool, it's been very useful.

I suggest a new feature, the tool being integrated into the `VS Code` side menu, where we could open the recent databases, and even configure by workspace to always open the same `database-dev.sqlite`, instead of going through the folders and opening the file manually.

![image](https://github.com/yy0931/sqlite3-editor/assets/43933482/806c9e62-394c-43c9-959e-25ad90d6c397)

original text
```
Sugiro uma nova funcionalidade, a ferramenta ser integrada no menu lateral do `VS Code`, onde poderíamos abrir os banco de dados recentes, e até configurar por workspace para abrir sempre o mesmo `database-dev.sqlite`, em vez de percorrer as pastas e abrir o arquivo manualmente.
```

**Comment by yy0931** [comment]
[We are not accepting feature requests now.](https://github.com/yy0931/sqlite3-editor/issues/51)
I believe you can achieve that by other means, such as creating shortcuts (symbolic links) or creating a shell script (batch file) that calls the `code` command to open the file.
