### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dh-coding** [yy0931/sqlite3-editor#58]
database disk image is malformed Query: SELECT schema, name, type FROM pragma_table_list WHERE NOT (name LIKE "sqlite\_%" ESCAPE "\") AND schema = 'main' COLLATE NOCASE Parameters: []

**Comment by yy0931** [comment]
Thanks for opening the issue, but I can't fix it without further information.

**Comment by dh-coding** [comment]
I was using live share, my friend was hosting it. Any SQLite3 database would show that error.

**Comment by yy0931** [comment]
Thanks for the information, I'll investigate it.

**Comment by yy0931** [comment]
After searching a bit, I found that we need to submit a request to the authors of Live Share for whitelisting this extension, like microsoft/live-share#5046, then we need to implement our logic for sharing data between hosts. However, I'm not seeing any incentive to do that much work.

**Comment by dh-coding** [comment]
Okay, fair enough. Thank you for looking into it.
