### ISSUE TITLE
despite pragmas are defined, makes dbs read-only.

### ISSUE THREAD

**Issue by tolgaulas** [yy0931/sqlite3-editor#60]
Despite the below vs-code settings, openening a file in sqlite3-editor locks the file for writing by other processes
vscode:
```
    "sqlite3-editor.connection.setupQueries": {
        ".*": "PRAGMA foreign_keys = ON; PRAGMA busy_timeout = 1000; PRAGMA cache_size = -1; PRAGMA journal_mode = WAL; PRAGMA synchronous = NORMAL;"
    },
 ```
error:
```
Type: SQLite3Exception
Code: 8
Message: attempt to write a readonly database
```
closing the file in the sqlite3-editor, removes this error.

**Comment by yy0931** [comment]
I cannot reproduce that error, so I cannot fix it.

It is strange that you're not receiving the usual `database is locked` error but instead `attempt to write a readonly database`, and I'm not sure what causes that.
