### ISSUE TITLE
Question: sql query editor while executing INSERT creates every time one extra empty row with NULL values?

### ISSUE THREAD

**Issue by mrlee14** [yy0931/sqlite3-editor#63]
version: v1.0.189

EXAMPLE:
INSERT INTO live_data ("ffmpeg_pid", "live_id", "service", "origin", "option", "date", "real_stat") 
VALUES (?, ?, ?, ?, ?, ?, ?), 
(12345, "asdadas", "youtube", "scheduler", NULL, 1723072696, 1723072699);

RESULT:
[{"ffmpeg_pid":12345,"live_id":"asdadas","service":"youtube","origin":"scheduler","option":null,"date":1723072696,"real_stat":1723072699}]

plus one extra row each time:
[{"live_id":null},{"ffmpeg_pid":null},{"service":null},{"origin":null},{"option":null},{"date":null},{"real_stat":null}]

Quetsion:  Is this bug or I have some unknown option set????

**Comment by yy0931** [comment]
I could not reproduce the issue.
1. Could you provide the schema of the `live_data` table?
2. Additionally, is there a trigger attached to the `live_data` table? You can check this via the Schema button in the UI.

**Comment by mrlee14** [comment]
> I could not reproduce the issue.
> 
> 1. Could you provide the schema of the `live_data` table?
> 2. Additionally, is there a trigger attached to the `live_data` table? You can check this via the Schema button in the UI.

NOTE: insert statements i execute by <shift+enter>

Schema: 
CREATE TABLE live_data (
                    ffmpeg_pid  INTEGER,
                    live_id     TEXT,
                    service     TEXT,
                    origin      TEXT,
                    option      TEXT,
                    date        INTEGER,
                    real_stat   INTEGER
                )

Triger:  None found

![Screenshot from 2024-08-17 02-11-07](https://github.com/user-attachments/assets/c786ddaf-710d-41a1-88e2-844b2a94005b)
![Screenshot from 2024-08-17 02-10-41](https://github.com/user-attachments/assets/41695aa1-c85e-458f-869a-23b44e8dffc1)

**Comment by yy0931** [comment]
Thank you, I now understand your question.
The query editor does not support placeholders, so the correct query would be:

```
INSERT INTO live_data ("ffmpeg_pid", "live_id", "service", "origin", "option", "date", "real_stat")
VALUES (12345, 'asdadas', 'youtube', 'scheduler', NULL, 1723072696, 1723072699);
```

What was happening in your original query is that in SQLite, a VALUES clause can make multiple rows by separating them with commas, like this:
```
sqlite> VALUES (1, 2), (3, 4), (5, 6);
column1
---
1|2
3|4
5|6
```

It seems SQLite treats unbound placeholders as NULL, so (?, ?, ?, ?, ?, ?, ?) is inserting 7 NULLs.
