### ISSUE TITLE
Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

### ISSUE THREAD

**Issue by TYTheBeast** [yy0931/sqlite3-editor#64]
![Screenshot_20240918_190406](https://github.com/user-attachments/assets/dab29c74-6040-4e3a-9621-df52d0f1d4ee)

Getting the error `Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..` whenever I try to open a database which I know is healthy because it opens fine in DB Browser for SQLite.

**Comment by yy0931** [comment]
I believe it is a bug in VSCode, not the extension. Could you follow this StackOverflow post? Please let us know if it does not help.

https://stackoverflow.com/questions/67698176/error-loading-webview-error-could-not-register-service-workers-typeerror-fai

**Comment by TYTheBeast** [comment]
The extension is working correctly again, thank you for the help and sorry for opening an issue without double checking StackOverflow!
