### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by TYTheBeast** [yy0931/sqlite3-editor#65]
```
Process exited: 101
thread 'main' panicked at src/list_placeholders.rs:59:44:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error code 6
```

Was editing a query when this happened.

**Comment by yy0931** [comment]
Thank you for reporting the issue.
There was a logic error, and I've fixed it in v1.0.193. (https://github.com/yy0931/sqlite3-editor/commit/74e4b2f904d1dd056c909e0959875709a340519b#diff-6aa30bc5183bf3c7d2435fb3fdc3a16781d107076c8320017955cd34f270db3d)
