### ISSUE TITLE
Should set current directory when executing sql.

### ISSUE THREAD

**Issue by heroboy** [yy0931/sqlite3-editor#66]
Currently, for example
```sql
ATTACH DATABASE 'a.db' as X;
```
Will accidentally create 'a.db' in the VSCode install directory.

Should set the current directory to the workspace directory or the same as the database file.

**Comment by yy0931** [comment]
Thanks. I've implemented this in v1.0.196.
The extension now sets the current directory of its child processes to the parent directory of the database file (except when the database file is in a virtual workspace or an in-memory database).
