### ISSUE TITLE
Cannot format .sql files

### ISSUE THREAD

**Issue by anthonymclaughlin** [yy0931/sqlite3-editor#8]
After installing the extension I can no longer format `.sql` files.

When I run `Format Document` from the Command Palette I get this error message: 

> There is no formatter for 'query-editor' files installed.

I have to disable the extension to get the formatting functionality back.

I'm using [Prettier SQL VSCode](https://marketplace.visualstudio.com/items?itemName=inferrinizzard.prettier-sql-vscode) by inferrinizzard as my sql file formatter.

**Comment by yy0931** [comment]
Click the button `SQLite3 Editor Query` in the status bar and change the language to `SQL (sql)`. I'll reduce the priority of this extension's language later.

![image](https://user-images.githubusercontent.com/54441600/215235296-341cfd5f-71a8-4494-a651-0d89a98ab6c2.png)

**Comment by yy0931** [comment]
Fixed in v1.0.48.
