### ISSUE TITLE
Setting to set custom font

### ISSUE THREAD

**Issue by eddyg** [yy0931/sqlite3-editor#9]
First, let me just say _"thanks!"_ for a great extension for VS Code! 🎉 It definitely makes working on and testing code that interacts with SQLite databases very convenient.

How hard would it be to add a setting that lets you set your own monospaced font for the UI? (Or ideally, default to the font set by the `editor.fontFamily` setting)?

Keep up the great work, and thanks again.

**Comment by yy0931** [comment]
It should be easy to implement. I will incorporate it in the next version.

**Comment by yy0931** [comment]
Resolved in v1.0.51.

**Comment by eddyg** [comment]
Thanks for the super-quick response time! ⚡ 

I use a narrow monospace programming font (similar to [Iosevka](https://typeof.net/Iosevka/)), and having the same font in SQLite3 Editor is great!

Thanks again! 🎉
